site_name: Nomadic
site_description: Mobile sequencing and analysis in real-time
repo_url: https://github.com/JasonAHendry/nomadic.git
theme:
  name: material
  palette:
  - scheme: default
    primary: blue grey
    accent: amber
  logo: img/little_logo.svg
  features:
  #  - navigation.tabs
    - navigation.sections
    - content.code.copy
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
extra_css:
  - css/custom.css
nav:
  - Overview: index.md
  - Installation: installation.md
  - Basic Usage: basic.md
  - Understanding the Dashboard: understand.md
  - Output Files & Sharing Data: output_files.md
  - Advanced Usage: advanced.md
  - FAQ: faq.md


