name: nomadic-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - minimap2
  - samtools
  - bcftools
  - htslib
  - bedtools
  - pysam
  - jupyter
  - dash
  - pandas
  - numpy
  - scipy
  - seaborn
  - click
  - black
  - flake8
  - pip
  - pytest
