name: nomadic-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >= 3.10
  - minimap2
  - samtools >=1.23
  - bcftools >=1.23
  - htslib
  - bedtools
  - delve-bio =0.3.*
  - pysam
  - jupyter
  - dash
  - pandas
  - openpyxl
  - numpy
  - statsmodels
  - seaborn
  - click
  - platformdirs
  - pyyaml
  - i18nice
  - pydantic
  - black
  - flake8
  - pip
  - pytest
  - mkdocs
  - mkdocs-material
  - pymdown-extensions
  - rsync
  - pip:
      - pytest-snapshot
