name: nomadic-dev
channels:
  - conda-forge
  - bioconda
dependencies:
  - python >= 3.10
  - minimap2
  - samtools >=1.20
  - bcftools >=1.20
  - htslib
  - bedtools
  - pysam
  - jupyter
  - dash
  - pandas
  - numpy
  - seaborn
  - click
  - platformdirs
  - pyyaml
  - i18nice
  - black
  - flake8
  - pip
  - pytest
  - mkdocs
  - mkdocs-material
  - pymdown-extensions
