name: build

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    defaults:
      run:
        shell: bash -el {0} # is needed for activation of conda environment via .profile

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.11"
          channels: bioconda,conda-forge
          channel-priority: true
          activate-environment: nomadic-dev
          environment-file: environments/dev.yml
          conda-remove-defaults: "true"

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Install nomadic package with Pip
        run: |
          pip install . --no-deps

      - name: Run tests
        run: |
          pytest
      
      - name: Smoke test package
        run: |
          nomadic --help


  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
