name: build

on:
  pull_request:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    defaults:
      run:
        shell: bash -el {0} # is needed for activation of conda environment via .profile

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          activate-environment: nomadic-dev

      - name: Get Date
        id: get-date
        run: echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache Conda env
        uses: actions/cache@v3
        with:
          path: ${{ env.CONDA }}/envs
          key:
            conda-${{ runner.os }}--${{ runner.arch }}--${{
            steps.get-date.outputs.today }}-${{
            hashFiles('environments/dev.yml') }}-${{ env.CACHE_NUMBER
            }}
        env:
          # Increase this value to reset cache if environments/dev.yml has not changed
          CACHE_NUMBER: 0
        id: cache

      - name: Update environment
        run:
          conda env update -n nomadic-dev -f environments/dev.yml
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Conda info
        run: |
          conda info
          conda list

      - name: Install nomadic package with Pip
        run: |
          pip install . --no-deps

      - name: Run tests
        run: |
          pytest
      
      - name: Smoke test package
        run: |
          nomadic --help


  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
